services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=retail_db
      - POSTGRES_USER=adison
      - POSTGRES_PASSWORD=secret_pass
    ports:
      - "5432:5432"

  web:
    image: adisondev/retail-store-api:v1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=retail_db
      - DB_USER=adison
      - DB_PASSWORD=secret_pass
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: