# Generated by Django 6.0.2 on 2026-02-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['phone'], name='users_custo_phone_d1790a_idx'), models.Index(fields=['name'], name='users_custo_name_e9a5fc_idx')],
            },
        ),
    ]
