# Generated by Django 6.0.2 on 2026-02-19 23:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='El nombre de la categoria es muy corto.')])),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='inventory_c_name_546ce4_idx'), models.Index(fields=['is_active'], name='inventory_c_is_acti_63d81f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(2, message='El nombre del producto es muy corto.')])),
                ('barcode', models.CharField(max_length=70, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='El precio no puede ser negativo.')])),
                ('stock_quantity', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['barcode'], name='inventory_p_barcode_3a77e5_idx'), models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'), models.Index(fields=['is_active'], name='inventory_p_is_acti_47a270_idx'), models.Index(fields=['category', 'is_active'], name='inventory_p_categor_471092_idx')],
            },
        ),
    ]
